name: Luap Studio CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Hello world action step
        uses: ./actions/ # Uses an action in the actions directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Run a one-line script
        run: echo Hello from Luap Studio

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo lol
